#-----------------------------------------------------#
#                                                     #
#                Database Properties                  #
#                                                     #
#-----------------------------------------------------#
default:
  adapter: 'mysql'
  database:
    host: 'localhost'
    port: 3306
    name: redseal
    username: 'root'
    password: 'nkrajan'